spring:
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/${DB_NAME:go2uz}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: coursemanagmentt@gmail.com
    password: rmtdqcbpmqabptsc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

payment:
  provider:
    url: https://api.paymentprovider.com/payment
    token: YOUR_ACCESS_TOKEN

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none

jwt:
  access-expiry: 86400000  # a day in milliseconds
  refresh-expiry: 604800000  # 7 days in milliseconds
  secret: gjhkoiutrefdsavzbxcnmktjyhretgwedfvbnjkrjyerhsfg
